/**
 * Loader and types for the pre-built city scene.
 *
 * Everything here is generated by `sim/network/build_city.py` from OpenStreetMap
 * data. Prop placements are validated against every road centreline at build time,
 * so the renderer can trust that nothing it draws sits on a carriageway.
 */
import { assertSceneOrigin } from "./geo";

export type PropInstance = {
  model: string;
  kind: string;
  x: number;
  z: number;
  yaw: number;
  scale: number;
  lat: number;
  lon: number;
};

export type RoadPolyline = {
  name: string;
  cls: string;
  half_width: number;
  rank: number;
  pts: [number, number][];
};

export type EdgeRegionGeo = {
  edge_id: string;
  name: string;
  latitude: number;
  longitude: number;
  x: number;
  z: number;
  yaw: number;
  coverage_radius_m: number;
  route_distance_m: number;
};

export type CityScene = {
  origin: { latitude: number; longitude: number };
  roads: RoadPolyline[];
  route: [number, number][];
  buildings: PropInstance[];
  trees: PropInstance[];
  props: PropInstance[];
  edge_regions: EdgeRegionGeo[];
};

export type AssetInfo = {
  size: [number, number, number];
  min_y: number;
  footprint: number;
  height: number;
  url: string;
};

export type AssetCatalog = Record<string, Record<string, AssetInfo>>;

let scenePromise: Promise<CityScene> | null = null;
let catalogPromise: Promise<AssetCatalog> | null = null;

export function loadCityScene(): Promise<CityScene> {
  if (!scenePromise) {
    scenePromise = fetch("/city/scene.json")
      .then((r) => {
        if (!r.ok) throw new Error(`city scene unavailable (${r.status})`);
        return r.json() as Promise<CityScene>;
      })
      .then((scene) => {
        assertSceneOrigin(scene.origin.latitude, scene.origin.longitude);
        return scene;
      });
  }
  return scenePromise;
}

export function loadAssetCatalog(): Promise<AssetCatalog> {
  if (!catalogPromise) {
    catalogPromise = fetch("/models/catalog.json").then((r) => {
      if (!r.ok) throw new Error(`asset catalog unavailable (${r.status})`);
      return r.json() as Promise<AssetCatalog>;
    });
  }
  return catalogPromise;
}

/** Group instances by model so each group can become one InstancedMesh. */
export function groupByModel(instances: PropInstance[]): Map<string, PropInstance[]> {
  const groups = new Map<string, PropInstance[]>();
  for (const inst of instances) {
    let bucket = groups.get(inst.model);
    if (!bucket) {
      bucket = [];
      groups.set(inst.model, bucket);
    }
    bucket.push(inst);
  }
  return groups;
}

/** Stable per-vehicle model choice, so a given traffic id always looks the same. */
export function pickTrafficModel(vehicleId: string, models: string[]): string {
  let hash = 0;
  for (let i = 0; i < vehicleId.length; i += 1) {
    hash = (hash * 31 + vehicleId.charCodeAt(i)) | 0;
  }
  return models[Math.abs(hash) % models.length];
}
